jarry_ubu_node:
    resource: "@JarryUbuBundle/Resources/config/routing/node.yml"
    prefix:   /place/{idPlace}/zone/{idZone}/node

jarry_ubu_zone:
    resource: "@JarryUbuBundle/Resources/config/routing/zone.yml"
    prefix:   /place/{idPlace}/zone

jarry_ubu_ubu_place:
    resource: "@JarryUbuBundle/Resources/config/routing/place.yml"
    prefix:   /place

jarry_ubu_homepage:
    path:     /
    defaults: { _controller: JarryUbuBundle:Default:index }

jarry_ubu_mentions:
    path:   /mentionslegales
    defaults: { _controller: JarryUbuBundle:Default:mentions }
