jarry_ubu_node:
    resource: "@JarryUbuBundle/Resources/config/routing/node.yml"
    prefix:   /node

jarry_ubu_zone:
    resource: "@JarryUbuBundle/Resources/config/routing/zone.yml"
    prefix:   /zone

jarry_ubu_ubu_place:
    resource: "@JarryUbuBundle/Resources/config/routing/place.yml"
    prefix:   /place

jarry_ubu_homepage:
    path:     /
    defaults: { _controller: JarryUbuBundle:Default:index }
