services:
#    jarry_ubu.example:
#        class: Jarry\UbuBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    jarry_ubu.registration.form.type:
        class: Jarry\UbuBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - {name: form.type, alias: ubu_user_registration}
