# src/Jarry/UbuBundle/Resources/config/doctrine/node.orm.yml
Jarry\UbuBundle\Entity\Node:
    type: entity
    table: node
    id:
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        ip_address:
            type: string
            length: 255
        name:
            type: string
            length: 255
    manyToOne:
        zone:
            targetEntity: Zone
            inversedBy: nodes
            joinColumn:
                name: zone_id
                referencedColumn: id
        node_type:
            targetEntity: NodeType
            inversedBy: nodes
            joinColumn:
                name: node_type_id
                referencedColumn: id