# src/Jarry/UbuBundle/Resources/config/doctrine/NodeType.orm.yml
Jarry\UbuBundle\Entity\NodeType:
    type: entity
    table: node_type
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        short_ref:
            type: string
            length: 255
    oneToMany:
        nodes:
            targetEntity: Node
            mappedBy: node_type