# src/Jarry/UbuBundle/Resources/config/doctrine/placeUser.orm.yml
Jarry\UbuBundle\Entity\PlaceUser:
    type: entity
    table: places_users
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    manyToOne:
        place:
            targetEntity: Place
            inversedBy: places_users
            joinColumn:
                name: place_id
                referencedColumnName: id
        user:
            targetEntity: User
            inversedBy: places_users
            joinColumn:
                name: user_id
                referencedColumnName: id