# src/Jarry/UbuBundle/Resources/config/doctrine/placeUser.orm.yml
Jarry\UbuBundle\Entity\PlaceUser:
    type: entity
    table: places_users
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        adress_street:
            type: string
            length: 255
        adress_number:
            type: string
            length: 25
        adress_city:
            type: string
            length: 255
        adress_zip:
            type: string
            length: 25
    manyToOne:
        place:
            targetEntity: Place
            inversedBy: places_users
            joinColumn:
                name: place_id
                referencedColumnName: id
        user:
            targetEntity: User
            inversedBy: places_users
            joinColumn:
                name: user_id
                referencedColumnName: id