# src/Jarry/UbuBundle/Resources/config/doctrine/user.orm.yml
Jarry\UbuBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        first_name:
            type: string
            length: 255
        last_name:
            type: string
            length: 255
        date_of_birth:
            type: datetime
        is_female:
            type: boolean
        locale:
            type: string
            length: 4
        time_zone:
            type: string
            length: 4
        address_purchase_street:
            type: string
            length: 255
            nullable: true
        address_purchase_number:
            type: string
            length: 25
            nullable: true
        address_purchase_city:
            type: string
            length: 255
            nullable: true
        address_purchase_zip:
            type: string
            length: 25
            nullable: true
        email:
            type: string
            length: 255
            unique: true
        profil_id:
            type: integer
        login:
            type: string
            length: 255
        password:
            type: string
            length: 255
        pepper:
            type: string
            length: 255
        facebook_id:
            type: integer
            nullable: true
        twitter_id:
            type: integer
            nullable: true
        google_plus_id:
            type: integer
            nullable: true
        enable_account:
            type: boolean
            default: true
        locking_account:
            type: boolean
        create_at:
            type: datetime
        last_login_at:
            type: datetime
            nullable: true
        folder_of_face:
            type: string
            length: 255
            nullable: true
        folder_of_voice:
            type: string
            length: 255
            nullable: true 
        td_model_fill_path:
            type: string
            length: 255
            nullable: true
        maps_path:
            type: string
            length: 255
            nullable: true
    oneToMany:
        places_users:
            targetEntity: PlaceUser
            mappedBy: user
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]