# src/Jarry/UbuBundle/Resources/config/doctrine/user.orm.yml
Jarry\UbuBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    oneToMany:
        places_users:
            targetEntity: PlaceUser
            mappedBy: user