ubu_place:
    path:     /
    defaults: { _controller: "JarryUbuBundle:Place:index" }

ubu_place_show:
    path:     /{id}
    defaults: { _controller: "JarryUbuBundle:Place:show" }
    requirements:
        id:    \d+

ubu_place_new:
    path:     /new
    defaults: { _controller: "JarryUbuBundle:Place:new" }

ubu_place_create:
    path:     /create
    defaults: { _controller: "JarryUbuBundle:Place:create" }
    methods:  POST

ubu_place_edit:
    path:     /{id}/edit
    defaults: { _controller: "JarryUbuBundle:Place:edit" }

ubu_place_update:
    path:     /{id}/update
    defaults: { _controller: "JarryUbuBundle:Place:update" }
    methods:  [POST, PUT]

ubu_place_delete:
    path:     /{id}/delete
    defaults: { _controller: "JarryUbuBundle:Place:delete" }
    methods:  [POST, DELETE]
    
ubu_place_share:
    path:   /{id}/share
    defaults: { _controller: "JarryUbuBundle:Place:sharePlace" }
    
ubu_place_share_send:
    path:   /{id}/send
    defaults: { _controller: "JarryUbuBundle:Place:sendPlace" }
    
ubu_place_join:
    path: /join
    defaults: { _controller: "JarryUbuBundle:Place:joinPlace" }
